### PR TITLE
add error check on pressure matching for Manifold EOS

### PR DESCRIPTION
**Pull request by baperry2**
In the Manifold EOS, the nominal pressure for the manifold model must be specified. This pressure should match the Pmean specified for PeleLMeX in the prob structure, although one is in cgs units and the other is in mks units.

### CODE REVIEW

**Comment by baperry2** [comment]
@justint1997

**Review by SreejithNREL — COMMENTED** [review]
Should we let the error tolerance be hard-coded to 1e-6 or let the user choose it?

**Comment by baperry2** [comment]
No need to make this user specifiable as it doesn't affect the solution. It's just there as a sanity check that the user is specifying valid inputs. 1e-6 is plenty to ensure that users don't forget to keep these values the same.

**Review by SreejithNREL — APPROVED** [review]
Looks good to me.

**Pull request merged**
