### PR TITLE
CVODE maxstep documentation

### PR DESCRIPTION
**Pull request by ThomasHowarth**
Adjusts documentation for PR in PelePhysics

### CODE REVIEW

**Comment by baperry2** [comment]
Looks good. Can you include the update to the PelePhysics submodule in this PR?

**Comment by baperry2** [comment]
Closes AMReX-Combustion/PelePhysics#480

**Comment by ThomasHowarth** [comment]
Hopefully that updated the submodule dependency

**Review by baperry2 — APPROVED** [review]
Yeah, the submodule update worked.

**Pull request merged**
