### PR TITLE
Add the interface for the radiation module

### PR DESCRIPTION
**Pull request by wjge**

### CODE REVIEW

**Comment by wjge** [comment]
Does PeleLMeX have a .clang-format?

**Comment by esclapez** [comment]
Hi Wenjun,

It does not, so the formatting requirements are pretty basic: no tabs, no trailing whitespaces. It looks like you have automatically reformatted the files you changed though.

**Comment by wjge** [comment]
> Hi Wenjun,
> 
> It does not, so the formatting requirements are pretty basic: no tabs, no trailing whitespaces. It looks like you have automatically reformatted the files you changed though.

Lucas,

Yeah. The automatic clang-format in my vim changed the format. I will try to use the format closer to the majority of original PeleLMeX code.

**Comment by baperry2** [comment]
Is there a test case that you can add to this PR to demonstrate? It would also be very helpful to add some documentation on the models and required input file parameters associated with radiation.

**Comment by wjge** [comment]
> Is there a test case that you can add to this PR to demonstrate? It would also be very helpful to add some documentation on the models and required input file parameters associated with radiation.

The test case for the coupled run is in the other PR in PeleMP
https://github.com/AMReX-Combustion/PeleMP/pull/14

and a script to build the test case on Frontier can be found here:
https://github.com/AMReX-Combustion/PeleMP/blob/00d262d3e75a566a4704ecb312558a7aadc5c5c8/Exec/JetTests/PeleLMeX/xburner_rad/script/build_Frontier.sh

Please let me know, if you have any issue building or running it.
Now I am trying to figure out a way to avoid pushing large checkpoint files, all the checkpoint files will be deleted soon in the PeleMP PR.

Although it is called a test, it is more like an example showing how to build and run with radiation. Most 'tests' in PeleMP serve for this purpose. Unit tests are included in the PeleRad repo:
https://github.com/AMReX-Combustion/PeleRad

We are documenting the multiphysics in the paper, and plan to add more notes on Github down the road.

**Comment by esclapez** [comment]
@wjge I'll test your script and move forward on this in the next couple of days.

**Comment by wjge** [comment]
Close it for now.

**Pull request closed without merging**
